Adapt examples to aarch64 (#11)
* Adding new build-test and syncing hello-world example

* Sync hello-world-crosscompiled

* Sync minimal-ml-inference

* Sync object-detector-cpp

* Sync object-detector-python

* Sync opencv-image-capture-cpp

* Sync opencv-qr-decoder-python

* Sync web-server

* In web-server example, setting as default arch armv7hf

* Fixing readme of object-detector-cpp and web-server

diff --git a/opencv-image-capture-cpp/Dockerfile b/opencv-image-capture-cpp/Dockerfile
--- a/opencv-image-capture-cpp/Dockerfile
+++ b/opencv-image-capture-cpp/Dockerfile
@@ -17,22 +17,45 @@ ENV https_proxy=$HTTP_PROXY
 ENV DEBIAN_FRONTEND=noninteractive
 
 ## Install dependencies
+ARG ARCH
 RUN apt-get update && apt-get install -y -f \
-    g++-arm-linux-gnueabihf \
-    make\
-    pkg-config \
-    libglib2.0-dev \
-    libsystemd0
+        make\
+        pkg-config \
+        libglib2.0-dev \
+        libsystemd0
 
-RUN dpkg --add-architecture armhf &&\
-    apt-get update && apt-get install -y  \
+RUN if [ "$ARCH" = armv7hf ]; then \
+        apt-get install -y -f \
+        g++-arm-linux-gnueabihf &&\
+        dpkg --add-architecture armhf &&\
+        apt-get update && apt-get install -y  \
         libglib2.0-dev:armhf \
-        libsystemd0:armhf
+        libsystemd0:armhf; \
+    elif [ "$ARCH" = aarch64 ]; then \
+        apt-get install -y -f \
+        g++-aarch64-linux-gnu &&\
+        dpkg --add-architecture arm64 &&\
+        apt-get update && apt-get install -y  \
+        libglib2.0-dev:arm64 \
+        libsystemd0:arm64; \
+    else \
+        printf "Error: '%s' is not a valid value for the ARCH variable\n", "$ARCH"; \
+        exit 1; \
+    fi
 
 COPY app/Makefile /build/
 COPY app/src/ /build/src/
 WORKDIR /build
-RUN make
+
+RUN if [ "$ARCH" = armv7hf ]; then \
+        make CXX=arm-linux-gnueabihf-g++ CC=arm-linux-gnueabihf-gcc  STRIP=arm-linux-gnueabihf-strip;\
+    elif [ "$ARCH" = aarch64 ]; then \
+        make  CXX=/usr/bin/aarch64-linux-gnu-g++ CC=/usr/bin/aarch64-linux-gnu-gcc STRIP=aarch64-linux-gnu-strip;\
+    else \
+        printf "Error: '%s' is not a valid value for the ARCH variable\n", "$ARCH"; \
+        exit 1; \
+    fi
+    
 
 FROM ${RUNTIME_IMAGE}
 COPY --from=cv-sdk-devel /build/capture_app /usr/bin/
diff --git a/web-server/Dockerfile b/web-server/Dockerfile
--- a/web-server/Dockerfile
+++ b/web-server/Dockerfile
@@ -1,12 +1,11 @@
-ARG UBUNTU_VERSION=20.04
+ARG ARCH=armv7hf
+ARG RUNTIME_IMAGE=arm32v7/ubuntu:20.04
 
-# A base image for crosscompilation
-FROM ubuntu:$UBUNTU_VERSION AS build-base
+FROM ${RUNTIME_IMAGE}
 
 # Setup environment variables
 ENV DEBIAN_FRONTEND=noninteractive
 ENV BUILD_ROOT=/build-root
-ENV CC="arm-linux-gnueabihf-gcc -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9"
 
 # Add source for target arch
 RUN echo \
@@ -21,46 +20,69 @@ deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ focal-security main
  > /etc/apt/sources.list
 
  ## Install dependencies
-RUN dpkg --add-architecture armhf &&\
-    apt-get update && apt-get install -y -f \
-    git \
-    make \
-    cmake \
-    pkg-config \
-    g++-arm-linux-gnueabihf \
-    libc-dev:armhf
+ARG ARCH
+RUN apt-get update && apt-get install -y -f \
+        git \
+        make\
+        cmake\
+        pkg-config \
+        libglib2.0-dev \
+        libsystemd0
 
-# Build server and library
-WORKDIR $BUILD_ROOT
-RUN git clone -b v1.5.6 https://github.com/monkey/monkey &&\
-    cd monkey &&\
-    mkdir -p build &&\
+RUN if [ "$ARCH" = armv7hf ]; then \
+        apt-get install -y -f \
+        g++-arm-linux-gnueabihf &&\
+        dpkg --add-architecture armhf &&\
+        apt-get update && apt-get install -y  \
+        libglib2.0-dev:armhf \
+        libc-dev:armhf \
+        libsystemd0:armhf; \
+    elif [ "$ARCH" = aarch64 ]; then \
+        apt-get install -y -f \
+        g++-aarch64-linux-gnu &&\
+        dpkg --add-architecture arm64 &&\
+        apt-get update && apt-get install -y  \
+        libglib2.0-dev:arm64 \
+        libc-dev:arm64 \
+        libsystemd0:arm64; \
+    else \
+        printf "Error: '%s' is not a valid value for the ARCH variable\n", "$ARCH"; \
+        exit 1; \
+    fi
+WORKDIR /opt
+COPY monkey.patch .
+
+RUN git clone -b v1.5.6 https://github.com/monkey/monkey
+WORKDIR /opt/monkey
+RUN git apply ../monkey.patch &&\
     ./configure \
-        --enable-shared \
-        --malloc-libc \
-        --prefix=/usr/local \
-        --plugdir=/usr/local/lib \
-        --pidfile=/usr/local/logs/monkey.pid \
-        --incdir=/usr/local/include/monkey \
-        --systemddir=/usr/lib/systemd/system \
-        --default-port=80 &&\
+    --enable-shared \
+    --malloc-libc \
+    --prefix=/usr/local \
+    --bindir=/usr/local/bin \
+    --libdir=/usr/local/lib \
+    --sysconfdir=/usr/local/packages/monkey/html \
+    --datadir=/usr/local/packages/monkey/html \
+    --mandir=/usr/local/man \
+    --logdir=/tmp \
+    --plugdir=/usr/local/packages/monkey/lib \
+    --pidfile=/tmp/monkey.pid \
+    --incdir=/usr/local/include/monkey \
+    --systemddir=/usr/lib/systemd/system &&\
     make &&\
     make install
 
+WORKDIR /opt/monkey/examples
+RUN cp /usr/local/bin/monkey .
+
 # Build examples
-ARG PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
-RUN cd monkey/examples &&\
-    sed -i 's/LDFLAGS/LDLIBS/g' Makefile &&\
+RUN sed -i 's/LDFLAGS/LDLIBS/g' Makefile &&\
     make &&\
     cp hello list quiz /usr/local/bin/
 
-# Create target image
-FROM arm32v7/ubuntu:$UBUNTU_VERSION
 ENV LD_LIBRARY_PATH=/usr/local/lib
-COPY --from=build-base /usr/local /usr/local
 
 # Prepare data for examples
 COPY . /tmp/
-
 # Start Monkey server
 CMD monkey
