refactor: use heredocs in dockerfiles (#88)

diff --git a/opencv-image-capture-cpp/Dockerfile b/opencv-image-capture-cpp/Dockerfile
--- a/opencv-image-capture-cpp/Dockerfile
+++ b/opencv-image-capture-cpp/Dockerfile
@@ -1,3 +1,5 @@
+# syntax=docker/dockerfile:1
+
 # Specify the architecture at build time: mipsis32r2el/armv7hf/aarch64
 # Should be used for getting API image
 # Currently, only armv7hf is supported
@@ -21,44 +23,42 @@ ENV DEBIAN_FRONTEND=noninteractive
 
 ## Install dependencies
 ARG ARCH
-RUN apt-get update && apt-get install -y -f \
-        make\
-        pkg-config \
-        libglib2.0-dev \
-        libsystemd0
+RUN <<EOF
+apt-get update
+apt-get install -y -f make pkg-config libglib2.0-dev libsystemd0
+EOF
 
-RUN if [ ${ARCH} = armv7hf ]; then \
-        apt-get install -y -f \
-        g++-arm-linux-gnueabihf &&\
-        dpkg --add-architecture armhf &&\
-        apt-get update && apt-get install -y  \
-        libglib2.0-dev:armhf \
-        libsystemd0:armhf; \
-    elif [ ${ARCH} = aarch64 ]; then \
-        apt-get install -y -f \
-        g++-aarch64-linux-gnu &&\
-        dpkg --add-architecture arm64 &&\
-        apt-get update && apt-get install -y  \
-        libglib2.0-dev:arm64 \
-        libsystemd0:arm64; \
-    else \
-        printf "Error: '%s' is not a valid value for the ARCH variable\n", ${ARCH}; \
-        exit 1; \
-    fi
+RUN <<EOF
+if [ ${ARCH} = armv7hf ]; then
+    apt-get install -y -f g++-arm-linux-gnueabihf
+    dpkg --add-architecture armhf
+    apt-get update
+    apt-get install -y libglib2.0-dev:armhf libsystemd0:armhf
+elif [ ${ARCH} = aarch64 ]; then
+    apt-get install -y -f g++-aarch64-linux-gnu
+    dpkg --add-architecture arm64
+    apt-get update
+    apt-get install -y libglib2.0-dev:arm64 libsystemd0:arm64
+else
+    printf "Error: '%s' is not a valid value for the ARCH variable\n", ${ARCH}
+    exit 1
+fi
+EOF
 
 COPY app/Makefile /build/
 COPY app/src/ /build/src/
 WORKDIR /build
 
-RUN if [ ${ARCH} = armv7hf ]; then \
-        make CXX=arm-linux-gnueabihf-g++ CC=arm-linux-gnueabihf-gcc  STRIP=arm-linux-gnueabihf-strip;\
-    elif [ ${ARCH} = aarch64 ]; then \
-        make  CXX=/usr/bin/aarch64-linux-gnu-g++ CC=/usr/bin/aarch64-linux-gnu-gcc STRIP=aarch64-linux-gnu-strip;\
-    else \
-        printf "Error: '%s' is not a valid value for the ARCH variable\n", ${ARCH}; \
-        exit 1; \
-    fi
-    
+RUN <<EOF
+if [ ${ARCH} = armv7hf ]; then
+    make CXX=arm-linux-gnueabihf-g++ CC=arm-linux-gnueabihf-gcc STRIP=arm-linux-gnueabihf-strip
+elif [ ${ARCH} = aarch64 ]; then
+    make  CXX=/usr/bin/aarch64-linux-gnu-g++ CC=/usr/bin/aarch64-linux-gnu-gcc STRIP=aarch64-linux-gnu-strip
+else
+    printf "Error: '%s' is not a valid value for the ARCH variable\n", ${ARCH}
+    exit 1
+fi
+EOF
 
 FROM runtime-image-${ARCH}
 COPY --from=cv-sdk-devel /build/capture_app /usr/bin/
diff --git a/web-server/Dockerfile b/web-server/Dockerfile
--- a/web-server/Dockerfile
+++ b/web-server/Dockerfile
@@ -1,3 +1,5 @@
+# syntax=docker/dockerfile:1
+
 ARG ARCH=armv7hf
 ARG UBUNTU_VERSION=22.04
 
@@ -12,41 +14,35 @@ ENV BUILD_ROOT=/build-root
 
  ## Install dependencies
 ARG ARCH
-RUN apt-get update && apt-get install -y -f \
-        git \
-        make\
-        cmake\
-        pkg-config \
-        libglib2.0-dev \
-        libsystemd0
+RUN <<EOF
+apt-get update
+apt-get install -y -f git make cmake pkg-config libglib2.0-dev libsystemd0
+EOF
 
-RUN if [ ${ARCH} = armv7hf ]; then \
-        apt-get install -y -f \
-        g++-arm-linux-gnueabihf &&\
-        dpkg --add-architecture armhf &&\
-        apt-get update && apt-get install -y  \
-        libglib2.0-dev:armhf \
-        libc-dev:armhf \
-        libsystemd0:armhf; \
-    elif [ ${ARCH} = aarch64 ]; then \
-        apt-get install -y -f \
-        g++-aarch64-linux-gnu &&\
-        dpkg --add-architecture arm64 &&\
-        apt-get update && apt-get install -y  \
-        libglib2.0-dev:arm64 \
-        libc-dev:arm64 \
-        libsystemd0:arm64; \
-    else \
-        printf "Error: '%s' is not a valid value for the ARCH variable\n", ${ARCH}; \
-        exit 1; \
-    fi
+RUN <<EOF
+if [ ${ARCH} = armv7hf ]; then
+    apt-get install -y -f g++-arm-linux-gnueabihf
+    dpkg --add-architecture armhf
+    apt-get update
+    apt-get install -y libglib2.0-dev:armhf libc-dev:armhf libsystemd0:armhf
+elif [ ${ARCH} = aarch64 ]; then
+    apt-get install -y -f g++-aarch64-linux-gnu
+    dpkg --add-architecture arm64
+    apt-get update
+    apt-get install -y libglib2.0-dev:arm64 libc-dev:arm64 libsystemd0:arm64
+else
+    printf "Error: '%s' is not a valid value for the ARCH variable\n", ${ARCH}
+    exit 1
+fi
+EOF
 WORKDIR /opt
 COPY monkey.patch .
 
 RUN git clone -b v1.5.6 https://github.com/monkey/monkey
 WORKDIR /opt/monkey
-RUN git apply ../monkey.patch &&\
-    ./configure \
+RUN <<EOF
+git apply ../monkey.patch
+./configure \
     --enable-shared \
     --malloc-libc \
     --prefix=/usr/local \
@@ -59,17 +55,20 @@ RUN git apply ../monkey.patch &&\
     --plugdir=/usr/local/packages/monkey/lib \
     --pidfile=/tmp/monkey.pid \
     --incdir=/usr/local/include/monkey \
-    --systemddir=/usr/lib/systemd/system &&\
-    make &&\
-    make install
+    --systemddir=/usr/lib/systemd/system
+make
+make install
+EOF
 
 WORKDIR /opt/monkey/examples
 RUN cp /usr/local/bin/monkey .
 
 # Build examples
-RUN sed -i 's/LDFLAGS/LDLIBS/g' Makefile &&\
-    make &&\
-    cp hello list quiz /usr/local/bin/
+RUN <<EOF
+sed -i 's/LDFLAGS/LDLIBS/g' Makefile
+make
+cp hello list quiz /usr/local/bin/
+EOF
 
 ENV LD_LIBRARY_PATH=/usr/local/lib
 
